### ISSUE TITLE
[META] Feature Model Viewer Usability Bugs and Enhancements

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#374]
* [x] Limits when zooming (e.g., 0.125 rem / 5rem)
* [x] OBDDimal/variability.dev#406
* [x] Middle mouse button click -> "fit to view"
* [x] OBDDimal/cofmed#1
* [x] Reset view should always switch back to top-down drawing and "fit to view"
* [x] OBDDimal/variability.dev#377
* [ ] "Adjust Levels" and "Adjust Max Children" does not work as expected
* [x] Tutorial should be cancelable via Esc, or click outside of the modal

Sidemenu -> Change Direction to Horizontally

* [x] Bug
When collapsing a feature, the triangle is not rotated:
![image](https://github.com/OBDDimal/variability.dev/assets/58979585/43137532-ddd5-476b-959b-09e357aed5d2)

* [x] Improvement: When changing in any direction, execute "fit to view" afterwards

Additions (2023-12-10): (see OBDDimal/variability.dev#420)
