### ISSUE TITLE
Initial User Management

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#6]
Django App: `core`

### Backend Tasks
* [x] #11
   * E-Mail (mandatory)
   * Markdown bio (optional)
   * Institution (optional)
   * GitHub Handle (optional)
   * Twitter Handle (optional)
* [x] #16
* [x] #18
* [x] #17
* [x] #24
* [x] #37
* [x] Override the default login form of Django

### Frontend Tasks
* [x] Landing page (not logged in) w/ button to login & button to register #31
* [x] Landing page (logged in) w/ button to logout #31
* [x] User Registration Modal #31
